sudo: required
language: ruby
addons:
  apt:
    sources:
    - sourceline: ppa:duggan/bats
    packages:
    - bats
    - bc
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login  --username "$DOCKER_USERNAME" --password-stdin
- ./build.sh
- ./test.sh
