name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
#  push:
#    branches: [ dev ]
#  pull_request:
#    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
    - uses: actions/checkout@v2
    - name: install lastversion
      run: sudo apt-get update -y; sudo apt-get install --no-install-recommends -y python3 python3-pip; pip install lastversion
    - name: Settings for this run
      run: echo Building Kimai images for version $(lastversion https://github.com/kevinpapst/kimai2)
    - name: Build the FPM Dev
      run: docker build . -t kimai/kimai2:fpm-$(lastversion https://github.com/kevinpapst/kimai2)-dev     --build-arg KIMAI=$(lastversion https://github.com/kevinpapst/kimai2) --build-arg BASE=fpm    --build-arg TZ=${TZ} --target=dev
    - name: Build the FPM Prod
      run: docker build . -t kimai/kimai2:fpm-$(lastversion https://github.com/kevinpapst/kimai2)-prod    --build-arg KIMAI=$(lastversion https://github.com/kevinpapst/kimai2) --build-arg BASE=fpm    --build-arg TZ=${TZ} --target=prod
    - name: Build the Apache Dev
      run: docker build . -t kimai/kimai2:apache-$(lastversion https://github.com/kevinpapst/kimai2)-dev  --build-arg KIMAI=$(lastversion https://github.com/kevinpapst/kimai2) --build-arg BASE=apache --build-arg TZ=${TZ} --target=dev
    - name: Build the Apache Prod
      run: docker build . -t kimai/kimai2:apache-$(lastversion https://github.com/kevinpapst/kimai2)-prod --build-arg KIMAI=$(lastversion https://github.com/kevinpapst/kimai2) --build-arg BASE=apache --build-arg TZ=${TZ} --target=prod

